'use client';
import { useState, useEffect } from 'react';
import { echangesApiService, type EchangesStats } from '@/lib/services/echangesApiService';
import { X, Zap, Clock, ArrowUp, MessageSquare, Timer, ArrowRight, CheckCircle } from 'lucide-react';
import { cn } from '@/lib/utils';
interface Props { open: boolean; onClose: () => void; }
export function EchangesDirectionPanel({ open, onClose }: Props) {
  const [stats, setStats] = useState<EchangesStats | null>(null);
  useEffect(() => { if (!open) return; const load = async () => { try { setStats(await echangesApiService.getStats()); } catch (e) { console.error(e); } }; load(); const i = setInterval(load, 30000); return () => clearInterval(i); }, [open]);
  if (!open) return null;
  return (<div className="fixed top-0 right-0 h-full w-80 bg-white dark:bg-[#1f1f1f] border-l border-slate-200 dark:border-slate-800 shadow-xl z-40 flex flex-col"><div className="flex-none p-4 border-b border-slate-200 dark:border-slate-800"><div className="flex items-center justify-between"><div><h3 className="font-semibold">Centre de Pilotage</h3><p className="text-xs text-slate-500">Échanges en temps réel</p></div><button onClick={onClose} className="p-1.5 rounded-lg hover:bg-slate-100 dark:hover:bg-slate-800"><X className="w-4 h-4" /></button></div></div><div className="flex-1 overflow-y-auto p-4 space-y-4">{!stats ? <div className="space-y-3 animate-pulse">{[...Array(4)].map((_, i) => <div key={i} className="h-20 rounded-xl bg-slate-100 dark:bg-slate-800" />)}</div> : <>{stats.urgentCount > 0 && <div className="p-3 rounded-xl bg-red-500/10 border border-red-500/30"><div className="flex items-center gap-2 mb-2"><Zap className="w-4 h-4 text-red-500" /><span className="font-semibold text-red-600">Urgents</span></div><p className="text-2xl font-bold text-red-600">{stats.urgentCount}</p><p className="text-xs text-red-500/80">Échanges prioritaires</p></div>}{stats.escalated > 0 && <div className="p-3 rounded-xl bg-amber-500/10 border border-amber-500/30"><div className="flex items-center gap-2 mb-2"><ArrowUp className="w-4 h-4 text-amber-500" /><span className="font-semibold text-amber-600">Escaladés</span></div><p className="text-2xl font-bold text-amber-600">{stats.escalated}</p><p className="text-xs text-amber-500/80">En attente de décision</p></div>}<div className="grid grid-cols-2 gap-3"><div className="p-3 rounded-xl bg-violet-500/10 border border-violet-500/20"><MessageSquare className="w-4 h-4 text-violet-500 mb-1" /><p className="text-xl font-bold text-violet-600">{stats.pending}</p><p className="text-xs text-slate-500">En attente</p></div><div className="p-3 rounded-xl bg-emerald-500/10 border border-emerald-500/20"><CheckCircle className="w-4 h-4 text-emerald-500 mb-1" /><p className="text-xl font-bold text-emerald-600">{stats.resolved}</p><p className="text-xs text-slate-500">Résolus</p></div></div><div className="p-3 rounded-xl bg-indigo-500/10 border border-indigo-500/30"><div className="flex items-center gap-2 mb-1"><Timer className="w-4 h-4 text-indigo-500" /><span className="text-sm font-medium">Temps moyen réponse</span></div><p className="text-2xl font-bold text-indigo-600">{stats.avgResponseTime}h</p></div></>}</div><div className="flex-none p-4 border-t border-slate-200 dark:border-slate-800"><p className="text-xs text-slate-500 text-center">Mise à jour auto toutes les 30s</p></div></div>);
}

